spring:
  application:
    name: java
  data :
    mongodb:
      database: myjournal
      auto-index-creation: true
      uri: ${MONGODB_URI}


server:
  port: 8080
  #servlet :
    # context-path: /journal


#logging:
  #level:
    #root: ERROR (Logs only ERROR-level messages from both the application and internal framework packages.)

