spring:
  application:
    name: java
  data:
    redis:
      uri: ${REDIS_URI}
  mongodb:
    database: myjournal
    auto-index-creation: true
    uri: ${MONGODB_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: warthog.lmq.cloudamqp.com
    port: 5671
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ejseeugf
    ssl:
      enabled: true
    requested-heartbeat: 30s
    connection-timeout: 30s
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

springdoc:
  swagger-ui:
    tagsSorter: alpha

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
elevenlabs:
  api:
    key: ${ELEVENLABS_API_KEY}
  voice-id: ${ELEVENLABS_VOICE_ID}

weather:
  api:
    key: ${WEATHER_API_KEY}
ai:
  service:
    base-url: https://journal-ai-service-1.onrender.com

server:
  port: ${PORT:8080}
    #servlet :
    # context-path: /journal



    #logging:
    #level:
    #root: ERROR (Logs only ERROR-level messages from both the application and internal framework packages.)
