spring:
  application:
    name: java
  mongodb:
    database: myjournal
    auto-index-creation: true
    uri: ${MONGODB_URI}


server:
  port: 8080
  #servlet :
    # context-path: /journal

elevenlabs:
  api:
    key: ${ELEVENLABS_API_KEY}
  voice-id: ${ELEVENLABS_VOICE_ID}

weather:
  api:
    key: ${WEATHER_API_KEY}



    #logging:
    #level:
    #root: ERROR (Logs only ERROR-level messages from both the application and internal framework packages.)
